# Generated by Django 5.0.6 on 2024-05-23 21:21

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0010_alter_publishedentry_summary'),
    ]

    operations = [
        migrations.RenameField(
            model_name='publishedentry',
            old_name='body',
            new_name='content',
        ),
    ]
