# Generated by Django 5.0.6 on 2024-05-24 00:48

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0012_alter_entry_options_entry_published_at'),
    ]

    operations = [
        migrations.DeleteModel(
            name='PublishedEntry',
        ),
    ]
