# Generated by Django 4.2.4 on 2023-08-31 01:11

from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Tag",
            fields=[
                (
                    "id",
                    models.AutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("name", models.CharField(max_length=50)),
                ("slug", models.SlugField(blank=True)),
            ],
            options={
                "ordering": ["created_at"],
                "abstract": False,
                "indexes": [
                    models.Index(
                        fields=["created_at"], name="blog_tag_created_33bfae_idx"
                    ),
                    models.Index(
                        fields=["updated_at"], name="blog_tag_updated_79a93a_idx"
                    ),
                ],
            },
        ),
        migrations.CreateModel(
            name="PublishedEntry",
            fields=[
                (
                    "id",
                    models.AutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("title", models.CharField(max_length=255)),
                ("slug", models.SlugField(blank=True)),
                ("summary", models.TextField()),
                ("body", models.TextField()),
                (
                    "card_image",
                    models.URLField(
                        blank=True,
                        help_text="URL to image for social media cards",
                        null=True,
                    ),
                ),
                (
                    "is_draft",
                    models.BooleanField(
                        default=False,
                        help_text="Draft entries do not show in index pages but can be visited directly if you know the URL",
                    ),
                ),
                ("tags", models.ManyToManyField(blank=True, to="blog.tag")),
            ],
            options={
                "verbose_name_plural": "published entries",
            },
        ),
    ]
