# Generated by Django 5.0.1 on 2024-01-16 14:19

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("blog", "0002_alter_entry_slug"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="entry",
            name="is_draft",
        ),
        migrations.AddField(
            model_name="entry",
            name="published_at",
            field=models.DateTimeField(
                blank=True, help_text="Date and time to publish the entry", null=True
            ),
        ),
    ]
