# Generated by Django 5.0.1 on 2024-01-16 16:37

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("blog", "0003_remove_entry_is_draft_entry_published_at"),
    ]

    operations = [
        migrations.AddField(
            model_name="entry",
            name="is_draft",
            field=models.GeneratedField(
                db_persist=False,
                expression=models.Case(
                    models.When(published_at__isnull=False, then=False), default=True
                ),
                help_text="Draft entries do not show in index pages but can be visited directly if you know the URL",
                output_field=models.BooleanField(),
            ),
        ),
    ]
