# Generated by Django 5.0.1 on 2024-01-17 18:52

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("blog", "0004_entry_is_draft"),
    ]

    operations = [
        migrations.CreateModel(
            name="Link",
            fields=[
                (
                    "id",
                    models.AutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("title", models.CharField(max_length=255)),
                ("slug", models.SlugField(blank=True, max_length=75)),
                (
                    "published_at",
                    models.DateTimeField(
                        blank=True,
                        help_text="Date and time to publish the entry",
                        null=True,
                    ),
                ),
                ("url", models.URLField()),
                ("via_title", models.CharField(blank=True, max_length=255)),
                ("via_url", models.URLField(blank=True)),
                ("comments", models.TextField(blank=True)),
                ("tags", models.ManyToManyField(blank=True, to="blog.tag")),
            ],
            options={
                "abstract": False,
            },
        ),
    ]
