# Generated by Django 5.0.1 on 2024-01-18 15:26

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("blog", "0005_link"),
    ]

    operations = [
        migrations.AddField(
            model_name="tag",
            name="description",
            field=models.TextField(blank=True),
        ),
        migrations.AlterField(
            model_name="tag",
            name="name",
            field=models.CharField(max_length=50, unique=True),
        ),
        migrations.AlterField(
            model_name="tag",
            name="slug",
            field=models.SlugField(blank=True, unique=True),
        ),
    ]
