# Generated by Django 5.0.1 on 2024-01-18 06:27

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("blog", "0005_link"),
    ]

    operations = [
        migrations.AddField(
            model_name="tag",
            name="description",
            field=models.TextField(blank=True),
        ),
    ]
