# Generated by Django 5.0.6 on 2024-05-23 18:57

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0007_alter_entry_slug_alter_link_slug'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Entry',
            new_name='PublishedEntry',
        ),
    ]
