# Generated by Django 5.0.6 on 2024-05-23 20:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0008_rename_entry_publishedentry'),
    ]

    operations = [
        migrations.CreateModel(
            name='Entry',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255)),
                ('slug', models.SlugField(blank=True, max_length=75, unique=True)),
                ('summary', models.TextField(blank=True)),
                ('content', models.TextField()),
            ],
        ),
    ]
