# Generated by Django 5.0.6 on 2024-05-24 00:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0011_rename_body_publishedentry_content'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='entry',
            options={'verbose_name_plural': 'entries'},
        ),
        migrations.AddField(
            model_name='entry',
            name='published_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
