# Generated by Django 5.0.6 on 2024-05-24 01:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0013_delete_publishedentry'),
    ]

    operations = [
        migrations.AddField(
            model_name='entry',
            name='updated_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
